
import { Project, DockItem } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'stage-visuals',
    title: 'Stage visuals',
    category: 'Various artists',
    description: "My animations made it beyond the computer screen and became part of live shows for artists like Kacperczyk, Fukaj, and Szaran. Stuff I was grinding out on my laptop ended up on big stages — during concert tours, Open'er, SBM FFestival, Hip-Hop Festival, Rap Stacja, Sun Festival, and even Męskie Granie. I love that something I create in full focus, just me and the screen, can later come to life — surrounded by lights, smoke, and a crowd of people.",
    thumbnail: 'https://picsum.photos/id/20/200/200',
    previewImage: 'https://picsum.photos/id/20/800/500',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    position: { top: '10%', left: '5%' },
  },
  {
    id: 'hotel-mafija',
    title: 'HOTEL MAFIJA VINYL',
    category: 'Print Design',
    description: 'Visual identity and vinyl packaging design for the Hotel Mafija project.',
    thumbnail: 'https://picsum.photos/id/30/200/200',
    previewImage: 'https://picsum.photos/id/30/800/600',
    position: { top: '5%', left: '40%' },
  },
  {
    id: 'efemmera',
    title: 'EFEMMERA',
    category: 'Visual Identity',
    description: 'Exploration of ephemeral visual concepts through digital media.',
    thumbnail: 'https://picsum.photos/id/40/200/200',
    previewImage: 'https://picsum.photos/id/40/800/600',
    position: { top: '12%', left: '50%' },
  },
  {
    id: 'kajecik',
    title: 'KAJECIK',
    category: 'App Design',
    description: 'A notebook application concept designed for creative professionals.',
    thumbnail: 'https://picsum.photos/id/50/200/200',
    previewImage: 'https://picsum.photos/id/50/800/600',
    position: { top: '15%', left: '75%' },
  },
  {
    id: 'wtf',
    title: 'WTF',
    category: 'Music Video',
    description: 'Direction and editing for the WTF music video.',
    thumbnail: 'https://picsum.photos/id/60/200/200',
    previewImage: 'https://picsum.photos/id/60/800/600',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    position: { top: '30%', left: '58%' },
  },
  {
    id: 'pierwszy-swag',
    title: 'PIERWSZY SWAG\nW POLSCE',
    category: 'Campaign',
    description: 'Marketing campaign visuals for a major polish fashion drop.',
    thumbnail: 'https://picsum.photos/id/70/200/200',
    previewImage: 'https://picsum.photos/id/70/800/600',
    position: { top: '35%', left: '42%' },
  },
  {
    id: 'trasa-konca',
    title: 'TRASA KOŃCA\nŚWIATA',
    category: 'Concert Visuals',
    description: 'Tour visuals for the End of the World Tour.',
    thumbnail: 'https://picsum.photos/id/80/200/200',
    previewImage: 'https://picsum.photos/id/80/800/600',
    position: { top: '40%', left: '52%' },
  },
  {
    id: 'collage-animations',
    title: 'COLLAGE ANIMATIONS',
    category: 'Motion Design',
    description: 'A series of experimental collage animations.',
    thumbnail: 'https://picsum.photos/id/90/200/200',
    previewImage: 'https://picsum.photos/id/90/800/600',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    position: { top: '45%', left: '56%' },
  },
  {
    id: 'interludium',
    title: 'INTERLUDIUM',
    category: 'Album Art',
    description: 'Cover art and promotional materials.',
    thumbnail: 'https://picsum.photos/id/100/200/200',
    previewImage: 'https://picsum.photos/id/100/800/600',
    position: { top: '32%', left: '77%' },
  },
  {
    id: 'trasa-po-koncu',
    title: 'TRASA\nPO KOŃCU ŚWIATA',
    category: 'Event Design',
    description: 'Post-apocalyptic event theming and visual direction.',
    thumbnail: 'https://picsum.photos/id/110/200/200',
    previewImage: 'https://picsum.photos/id/110/800/600',
    position: { top: '38%', left: '80%' },
  },
  {
    id: 'solar-bialas',
    title: 'SOLAR X BIAŁAS',
    category: 'Branding',
    description: 'Collaborative branding project.',
    thumbnail: 'https://picsum.photos/id/120/200/200',
    previewImage: 'https://picsum.photos/id/120/800/600',
    position: { top: '50%', left: '70%' },
  },
  {
    id: 'chanel',
    title: 'CHANEL',
    category: 'Commercial',
    description: 'Unofficial commercial concept for Chanel fragrance.',
    thumbnail: 'https://picsum.photos/id/130/200/200',
    previewImage: 'https://picsum.photos/id/130/800/600',
    position: { top: '55%', left: '79%' },
  },
  {
    id: 'sbm-ff24',
    title: 'SBM FF24',
    category: 'Festival',
    description: 'Main stage visuals for SBM FF24.',
    thumbnail: 'https://picsum.photos/id/140/200/200',
    previewImage: 'https://picsum.photos/id/140/800/600',
    position: { top: '45%', left: '88%' },
  },
  {
    id: 'newonce',
    title: 'NEWONCE',
    category: 'Media',
    description: 'Graphics package for Newonce radio.',
    thumbnail: 'https://picsum.photos/id/150/200/200',
    previewImage: 'https://picsum.photos/id/150/800/600',
    position: { top: '65%', left: '62%' },
  },
  {
    id: 'merch',
    title: 'MERCH',
    category: 'Fashion',
    description: 'Merchandise design collection.',
    thumbnail: 'https://picsum.photos/id/160/200/200',
    previewImage: 'https://picsum.photos/id/160/800/600',
    position: { top: '64%', left: '52%' },
  },
  {
    id: 'fantasmagorie',
    title: 'FANTASMAGORIE',
    category: 'Art',
    description: 'Surrealist digital art series.',
    thumbnail: 'https://picsum.photos/id/170/200/200',
    previewImage: 'https://picsum.photos/id/170/800/600',
    position: { top: '70%', left: '45%' },
  },
  {
    id: 'ryk-x-sexed',
    title: 'RYK X SEXED',
    category: 'Campaign',
    description: 'Social awareness campaign graphics.',
    thumbnail: 'https://picsum.photos/id/180/200/200',
    previewImage: 'https://picsum.photos/id/180/800/600',
    position: { top: '78%', left: '72%' },
  },
];

export const DOCK_ITEMS: DockItem[] = [
  { label: 'After Effects', iconType: 'ae' },
  { label: 'Photoshop', iconType: 'ps' },
  { label: 'Illustrator', iconType: 'ai' },
  { label: 'Alerts', iconType: 'warning' },
  { label: 'Notes', iconType: 'notes' },
  { label: 'Photos', iconType: 'photos' },
  { label: 'Instagram', iconType: 'insta' },
  { label: 'Contact', iconType: 'mail' },
  { label: 'Trash', iconType: 'trash' },
];
